name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Thunder Client CLI
        run: npm install -g @thunderclient/cli

      - name: Make directory for reports
        run: mkdir -p thunder-reports

      - name: Run Collection
        run: tc --col "Ecommerce API" --env "dev" --report cli,json

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: thunder-reports
          path: thunder-reports/
